version: '3.8'

services:
  nextjs-app:
    container_name: nextjs-app-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    restart: unless-stopped
